id: template_chat_flow
name: Template Chat Flow
inputs:
  chat_history:
    type: list
    is_chat_input: false
    is_chat_history: true
  question:
    type: string
    is_chat_input: true
outputs:
  answer:
    type: string
    reference: ${chat.output}
    is_chat_output: true
nodes:
- name: question_embedding
  type: python
  source:
    type: package
    tool: promptflow.tools.embedding.embedding
  inputs:
    connection: Default_AzureOpenAI
    deployment_name: text-embedding-ada-002
    input: ${inputs.question}
  use_variants: false
- name: products
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://nh-aoai-canada.openai.azure.com/
        api_type: azure
        api_version: 2023-07-01-preview
        batch_size: '1'
        connection:
          id: /subscriptions/0a7cca23-9daf-45df-8429-20321cce9d90/resourceGroups/rg-niheiai/providers/Microsoft.MachineLearningServices/workspaces/nhtest1/connections/Default_AzureOpenAI
        connection_type: workspace_connection
        deployment: text-embedding-ada-002
        dimension: 1536
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: 2023-07-01-preview
        connection:
          id: /subscriptions/0a7cca23-9daf-45df-8429-20321cce9d90/resourceGroups/rg-niheiai/providers/Microsoft.MachineLearningServices/workspaces/nhtest1/connections/AzureAISearch
        connection_type: workspace_connection
        endpoint: https://nhaoaicogsearch.search.windows.net
        engine: azure-sdk
        field_mapping:
          content: content
          embedding: contentVector
          metadata: meta_json_string
        index: contoso-products
        kind: acs
        semantic_configuration_name: azureml-default
    queries: ${question_embedding.output}
    query_type: Hybrid + semantic
    top_k: 3
  use_variants: false
- name: chat
  type: llm
  source:
    type: code
    path: chat.jinja2
  inputs:
    deployment_name: ""
    temperature: 0.7
    max_tokens: 256
    question: ${inputs.question}
    chat_history: ${inputs.chat_history}
  provider: AzureOpenAI
  connection: ""
  api: chat
  use_variants: false
node_variants: {}
environment:
  python_requirements_txt: requirements.txt
