id: template_chat_flow
name: Template Chat Flow
inputs:
  chat_history:
    type: list
    is_chat_input: false
    is_chat_history: true
  question:
    type: string
    is_chat_input: true
outputs:
  answer:
    type: string
    reference: ${chat.output}
    is_chat_output: true
nodes:
- name: question_embedding
  type: python
  source:
    type: package
    tool: promptflow.tools.embedding.embedding
  inputs:
    connection: Default_AzureOpenAI
    deployment_name: text-embedding-ada-002
    input: ${inputs.question}
  use_variants: false
- name: products
  type: python
  source:
    type: package
    tool: promptflow_vectordb.tool.common_index_lookup.search
  inputs:
    mlindex_content: >
      embeddings:
        api_base: https://nh-aoai-canada.openai.azure.com/
        api_type: Azure
        api_version: 2023-07-01-preview
        batch_size: '16'
        connection:
          id: 
            /subscriptions/0a7cca23-9daf-45df-8429-20321cce9d90/resourceGroups/rg-niheiai/providers/Microsoft.MachineLearningServices/workspaces/nhtest1/connections/Default_AzureOpenAI
        connection_type: workspace_connection
        deployment: text-embedding-ada-002
        dimension: 1536
        file_format_version: '2'
        kind: open_ai
        model: text-embedding-ada-002
        schema_version: '2'
      index:
        api_version: 2023-07-01-preview
        connection:
          id: 
            /subscriptions/0a7cca23-9daf-45df-8429-20321cce9d90/resourceGroups/rg-niheiai/providers/Microsoft.MachineLearningServices/workspaces/nhtest1/connections/AzureAISearch
        connection_type: workspace_connection
        endpoint: https://nhaoaicogsearch.search.windows.net
        engine: azure-sdk
        field_mapping:
          content: content
          embedding: contentVector
          filename: filepath
          metadata: meta_json_string
          title: title
          url: url
        index: contosotxt
        kind: acs
        semantic_configuration_name: azureml-default
      self:
        path: 
          azureml://subscriptions/0a7cca23-9daf-45df-8429-20321cce9d90/resourcegroups/rg-niheiai/workspaces/nhtest1/datastores/workspaceblobstore/paths/azureml/49a8308f-d0a6-4936-866b-89b8b5ae485f/index/
        asset_id: 
          azureml://locations/eastus/workspaces/9bb59072-5add-4b1d-b3c9-8fcfd967757d/data/contosotxt/versions/1
    queries: ${inputs.question}
    query_type: Hybrid (vector + keyword)
    top_k: 3
  use_variants: false
- name: prompt
  type: prompt
  source:
    type: code
    path: prompt.jinja2
  inputs:
    documentation: ${products.output}
    history: ${inputs.chat_history}
  use_variants: false
- name: chat
  type: llm
  source:
    type: code
    path: chat.jinja2
  inputs:
    deployment_name: gpt-35-turbo-16k
    temperature: 0.7
    top_p: 1
    max_tokens: 256
    presence_penalty: 0
    frequency_penalty: 0
    prompt_text: ${prompt.output}
    question: ${inputs.question}
  provider: AzureOpenAI
  connection: Default_AzureOpenAI
  api: chat
  module: promptflow.tools.aoai
  use_variants: false
node_variants: {}
environment:
  python_requirements_txt: requirements.txt
